package wrapping

import (
	"bytes"
	"crypto/aes"
	"encoding/binary"
	"errors"
)

// WARNING - THIS IS NOT SUITABLE FOR PRODUCTION SYSTEMS.
// DO NOT RELY ON THIS IMPLEMENTATION.
// Designed only to meet the needs of local-kms.

// AesKeyUnwrapWithPadding implements **AES Key Unwrap with Padding**
// as specified in **RFC 5649**.
//
// This is required by AWS KMS for the wrapping algorithms:
//   - RSA_AES_KEY_WRAP_SHA_1
//   - RSA_AES_KEY_WRAP_SHA_256
//
// --- Why this exists ---------------------------------------------------------
//
// AWS KMS does NOT use:
//   - RFC 3394 (AES Key Wrap without padding)
//   - AES-GCM
//   - Raw RSA encryption of key material
//
// Instead, KMS uses a *hybrid* scheme:
//
//  1. A random AES Key-Encryption Key (KEK) is generated by the client
//
//  2. The actual key material is wrapped using RFC 5649 (AES-KWP)
//
//  3. The KEK is encrypted using RSAES-OAEP (SHA-1 or SHA-256)
//
//  4. The final ciphertext is:
//
//     RSA(KEK) || AES_KWP(key_material)
//
// The AES portion is variable-length and requires padding, which is
// why RFC 5649 is used instead of RFC 3394.
//
// --- High-level algorithm ----------------------------------------------------
//
// RFC 5649 is an extension of RFC 3394 that supports arbitrary-length
// plaintext by encoding the message length inside the wrapped data.
//
// The wrapped output has the form:
//
//	C[0] || C[1] || ... || C[n]
//
// Where:
//   - C[0] is a special 64-bit value called the AIV (Alternative Initial Value)
//   - C[1..n] are 64-bit blocks of encrypted payload
//
// The AIV layout is:
//
//	AIV = 0xA65959A6 || MLI
//
//	- 0xA65959A6 is a fixed 32-bit magic value
//	- MLI (Message Length Indicator) is a 32-bit big-endian integer
//	  representing the original plaintext length in bytes
//
// --- Inputs ------------------------------------------------------------------
//
//	kek     - AES Key-Encryption Key (16, 24, or 32 bytes)
//	wrapped - RFC 5649 wrapped key material
//
// Constraints:
//   - wrapped must be >= 16 bytes
//   - wrapped length must be a multiple of 8 bytes
//
// --- Outputs -----------------------------------------------------------------
//
//	plaintext key material, truncated to exactly MLI bytes
//
// --- Security notes ----------------------------------------------------------
//
//   - All cryptographic operations are constant-time at the AES level
//   - Padding validity is verified using the AIV and MLI
//   - Any failure MUST be treated as InvalidCiphertextException at the KMS API
//
// --- Implementation details --------------------------------------------------
//
//	The unwrap process runs 6 * n AES decryptions, where n is the number
//	of 64-bit blocks minus one. This mirrors RFC 3394 but with a different
//	initial value and length handling.
//
//	This function is intentionally strict:
//	  - Rejects invalid AIV
//	  - Rejects invalid length indicators
//	  - Rejects malformed block sizes
//
//	This behaviour matches AWS KMS and OpenSSL's
//	`-id-aes256-wrap-pad` implementation.
//
// --- References --------------------------------------------------------------
//
//	RFC 5649: https://datatracker.ietf.org/doc/html/rfc5649
//	RFC 3394: https://datatracker.ietf.org/doc/html/rfc3394
//	AWS KMS ImportKeyMaterial documentation
func AesKeyUnwrapWithPadding(kek, wrapped []byte) ([]byte, error) {
	// RFC 5649: wrapped must be >= 16 bytes and multiple of 8
	if len(wrapped) < 16 || (len(wrapped)%8) != 0 {
		return nil, errors.New("rfc5649: invalid wrapped length")
	}

	block, err := aes.NewCipher(kek)
	if err != nil {
		return nil, err
	}

	// n = number of 64-bit blocks minus 1
	n := (len(wrapped) / 8) - 1

	// A is 64-bit
	A := make([]byte, 8)
	copy(A, wrapped[:8])

	// R[1]..R[n]
	R := make([][]byte, n)
	for i := 0; i < n; i++ {
		R[i] = make([]byte, 8)
		copy(R[i], wrapped[8*(i+1):8*(i+2)])
	}

	// 6 rounds in reverse
	buf := make([]byte, 16)
	for j := 5; j >= 0; j-- {
		for i := n - 1; i >= 0; i-- {
			// t = n*j + (i+1)
			t := uint64(n*j + (i + 1))

			// B = AES-1( (A ^ t) | R[i] )
			for k := 0; k < 8; k++ {
				buf[k] = A[k] ^ byte(t>>(56-8*k))
			}
			copy(buf[8:], R[i])

			block.Decrypt(buf, buf)
			copy(A, buf[:8])
			copy(R[i], buf[8:])
		}
	}

	// Check alternative initial value (AIV): 0xA6 59 59 A6 || MLI (32-bit big-endian)
	if !bytes.Equal(A[:4], []byte{0xA6, 0x59, 0x59, 0xA6}) {
		return nil, errors.New("rfc5649: invalid AIV")
	}

	m := int(binary.BigEndian.Uint32(A[4:])) // MLI
	if m < 0 || m > 8*n {
		return nil, errors.New("rfc5649: invalid MLI")
	}

	// Reassemble P = R[1]..R[n], then truncate to MLI
	out := make([]byte, 0, 8*n)
	for i := 0; i < n; i++ {
		out = append(out, R[i]...)
	}

	return out[:m], nil
}
